// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", true);
user_pref("app.normandy.startupRolloutPrefs.editor.truncate_user_pastes", true);
user_pref("app.normandy.user_id", "aeb5ee81-bf1b-4b12-99c9-e2335bbd7280");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1595071213);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1595071189);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1595071185);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1595071243);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3777);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595071182);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{57d43970-7fb0-4638-a7a4-55dd2bc9a05a}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1595071210956");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1595073027956");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1595071186124");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1595074786124");
user_pref("browser.slowStartup.averageTime", 1905);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1595071183);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1595071184986");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "6c865b6b259a4ad78afda524ce766c2e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0fb149e7-fc6d-4e31-93a5-54b8b76339f3\",\"formautofill@mozilla.org\":\"256f8957-3075-48f6-8183-c4efbefaa856\",\"screenshots@mozilla.org\":\"6b2b8f85-9741-43a8-8867-e6cc08f8c904\",\"webcompat-reporter@mozilla.org\":\"cc33bf14-134a-4def-b36f-3563fe6106ea\",\"webcompat@mozilla.org\":\"143b5416-3e01-48ee-9ffd-02d1eaecbef6\",\"default-theme@mozilla.org\":\"8638d856-bf89-4ac3-98f0-df04af192a69\",\"google@search.mozilla.org\":\"7943cb54-7e04-4995-b714-44098115658f\",\"amazondotcom@search.mozilla.org\":\"ff0260b5-f391-4a43-ab04-6ac75601b40a\",\"bing@search.mozilla.org\":\"774bafb2-9d3b-4a6e-a40e-e4ae633e9b17\",\"ddg@search.mozilla.org\":\"ccf3f673-57d3-40f4-ae9b-397d8a62eb0e\",\"ebay@search.mozilla.org\":\"fc57702c-aeaa-4ed6-9892-9417ad47acd1\",\"twitter@search.mozilla.org\":\"bc9695c4-d931-4c63-b855-8ef7a071832f\",\"wikipedia@search.mozilla.org\":\"8efdd969-8543-43c4-9176-67c3b0ef4008\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1595071258);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1595071257);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1595071258);
user_pref("security.remote_settings.intermediates.checked", 1595071258);
user_pref("security.sandbox.content.tempDirSuffix", "a952c374-dd6e-4058-8bed-f1418f4d46ba");
user_pref("security.sandbox.plugin.tempDirSuffix", "ee98abbf-0c82-4b2a-8b30-6a09b12daa52");
user_pref("services.blocklist.addons.checked", 1595071258);
user_pref("services.blocklist.gfx.checked", 1595071258);
user_pref("services.blocklist.pinning.checked", 1595071258);
user_pref("services.blocklist.plugins.checked", 1595071258);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1595015675135\"");
user_pref("services.settings.last_update_seconds", 1595071258);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1595071258);
user_pref("services.settings.main.cfr-fxa.last_check", 1595071258);
user_pref("services.settings.main.cfr.last_check", 1595071258);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1595071258);
user_pref("services.settings.main.hijack-blocklists.last_check", 1595071258);
user_pref("services.settings.main.language-dictionaries.last_check", 1595071258);
user_pref("services.settings.main.messaging-experiments.last_check", 1595071258);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1595071258);
user_pref("services.settings.main.public-suffix-list.last_check", 1595071258);
user_pref("services.settings.main.search-config.last_check", 1595071258);
user_pref("services.settings.main.sites-classification.last_check", 1595071258);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1595071258);
user_pref("services.settings.main.whats-new-panel.last_check", 1595071258);
user_pref("services.settings.security.onecrl.checked", 1595071258);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1595071181);
user_pref("toolkit.telemetry.cachedClientID", "5c6aae1d-2460-4ef8-8487-ca29466e3701");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
