#!/bin/zsh

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
export VIEB_WINDOW_FRAME=true

# Import display variable for dunst
systemctl --user import-environment DISPLAY

xset s off
xset r rate 180 55
setxkbmap -option caps:escape
setxkbmap dk
#xmodmap -e "keycode 107 = Menu NoSymbol Menu"

autorandr

dunst& unclutter& numlockx& sxhkd& picom&

~/.local/bin/set_wp

# Attempt starting PulseAudio daemon?
pulseaudio --start

~/.local/bin/dwmstatus &
exec /usr/local/bin/dwm
